### ISSUE TITLE
Enhance Deployment Options for Low-Memory VPS

### ISSUE THREAD

**Issue by slchris** [slchris/drep-server#1]
For VPS instances with very limited memory, deploying using binary files is a better option.

**TODO**

- [ ] Use GitHub Actions to build binary artifacts and upload them to GitHub Releases.
- [ ] Add support for systemd.
- [ ] Add an Ansible playbook to support deployment via Docker or binary files.

**Comment by slchris** [comment]
- [ ] DEB
